### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by joshpetit** [tjysdsg/wer#1]
bruh

**Comment by tjysdsg** [comment]
Dude what's up lol

**Comment by joshpetit** [comment]
nothing much haha. coding n stuff. hbu make any new apps?

**Comment by tjysdsg** [comment]
ah im doing intern and stuff, researching pronunciation evaluation

**Comment by joshpetit** [comment]
that's some advanced stuff. im doing front-end web dev, which is pretty fun, besides css.

**Comment by tjysdsg** [comment]
bruh css is a disaster

**Comment by joshpetit** [comment]
facts. do you still do flutter? im going to be doing a lot of it on the side the next few months. dart's dope tho so I don't mind, beats css any day.

**Comment by tjysdsg** [comment]
i don't use it currently, the project that I was building a client for is paused now. but I agree dart is dope haha

**Comment by tjysdsg** [comment]
it's rare to see u at US midnight lol

**Comment by joshpetit** [comment]
midnight? nah haha it was about 10 pm when I sent that message. I've stayed up later during the summer but ive gotten less sleep as of recent.

**Comment by joshpetit** [comment]
yea have fun with `wer` tho.

**Comment by tjysdsg** [comment]
ha you too with ur summer
